
import type { Metadata } from "next";
import "../globals.css";
import PageWrapper from "@/compontents/ui/layout/PageWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: {
    canonical: `https://yourwebsite.com/en`,
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="description"></meta>
        <meta name="robots" content="index, follow" />
        <link
          rel="shortlink"
          href={`${process.env.NEXT_PUBLIC_MAIN_SITE}/${locale}`}
        />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/favicon.ico`}
          type="image/x-icon"
        />
        <meta
          property="og:url"
          content={`${process.env.NEXT_PUBLIC_MAIN_SITE}/${locale}`}
        />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className="font-avenir">
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}